### PR TITLE
refact: use f-string instead of format

### PR DESCRIPTION
**Pull request by EwertonBello**

### CODE REVIEW

**Review by mcarlton00 — CHANGES_REQUESTED** [review]
f-strings in `build.py` are fine, but anywhere else will break compatibility with Kodi 18 which we can't do yet

**Comment by EwertonBello** [comment]
> f-strings in `build.py` are fine, but anywhere else will break compatibility with Kodi 18 which we can't do yet

I understand, I will make the changes.

**Comment by EwertonBello** [comment]
@mcarlton00 Could you include the label “HACKTOBERFEST-ACCEPTED” in the MR please?

**Comment by mcarlton00** [comment]
Since the `hacktoberfest` label is on the repo, there's no reason to add labels to individual PRs

**Review by mcarlton00 — APPROVED** [review]

**Pull request merged**
