### PR TITLE
Fix `Flatten single season` do not respect `Show empty folders (shows, seasons, collections)` disabled

### PR DESCRIPTION
**Pull request by aiosk**
**Condition**
- I have series with season not released yet.
- I have enabled `Settings > Display > Display missing episodes within seasons` on Jellyfin.
- I have enabled `Add-on Actions > Show add-on settings >  Interface > Item Details > Flatten single season` on Jellycon
- I have disabled `Add-on Actions > Show add-on settings >  Interface > Item Details > Show empty folders (shows, seasons, collections)` on Jellycon

**Expected**
- Series with single season display list of episodes

**Actual**
- Series with single season display single season

**Probable Cause**
- Jellycon include missing seasons when getting items from jellyfin server
- `Flatten single season` logic do not respect `Show empty folders` setting when processing `item.is_folder == True`.

This patch add process to filter empty folders (missing seasons and my `Subs` season) when `Show empty folders` is enabled on jellycon settings before add item to gui.

Feel free to reject this PR if **Actual Result** is supposed to happen

<details>
<summary><b>Probably bug / misconfigured server</b></summary>

---

**Condition**
- Jellyfin 10.8.1
- I have series with single season.
- I have `Subs` folder in series folder, containing multiple subtitles in available language per episodes folder
  ```
  - SeriesName
    - Subs
      - SeriesName - S01E01
        - en.srt
        - en.sdh.srt
      - SeriesName - S01E02
        - en.srt
        - en.sdh.srt
    - SeriesName - S01E01.mp4
    - SeriesName - S01E01.en.srt
    - SeriesName - S01E02.mp4
    - SeriesName - S01E02.en.srt
  ```
- I have enabled `Settings > Display > Display missing episodes within seasons` on Jellyfin.
- I have enabled `Add-on Actions > Show add-on settings >  Interface > Item Details > Flatten single season` on Jellycon
- I have disabled `Add-on Actions > Show add-on settings >  Interface > Item Details > Show empty folders (shows, seasons, collections)` on Jellycon

**Expected**
- Series with single season display list of episodes

**Actual**
- Jellyfin treat my `Subs` folder as a season
- Series with single season display single season

**Probable Cause**
- Jellycon include my `Subs` seasons when getting items from jellyfin server
- `Flatten single season` logic do not respect `Show empty folders` setting when processing `item.is_folder == True`.
</details>

### CODE REVIEW

**Comment by mcarlton00** [comment]
I think the root of this is that jellyfin doesn't support a separate subs folder, afaik.  It expects your subtitles to be next to your media and named identically to the linked items with different extensions.  The [external files](https://jellyfin.org/docs/general/server/media/external-files.html) page of the docs has a bit more detail of the options.

Or I could be wrong and it's undocumented and works fine, but you're throwing a monkey wrench into the scanner by not having your files in a season directory.  Basically, the scanner expects your episodes to be inside a season directory with the relevant external files named identically next to them.

    show name
      season XX
        episode S0XEXX.mkv
        episode S0XEXX.srt

or

    show name
      episode S0XEXX.mkv
      episode S0XEXX.srt

However, what you've done with your structure is kinda combine the two approaches and possibly confusing the server into thinking all the individual episodes are fine, _and_ the separate subs folder is it's own season.  So I'm guessing you're winding up with duplicate entries, possibly linked together.  If it's working in the server as you expect, I'd be super surprised.  I just tried moving some subs into a separate folder and they're not being scanned in at all

**Comment by aiosk** [comment]
<details>


> I think the root of this is that jellyfin doesn't support a separate subs folder, afaik. It expects your subtitles to be next to your media and named identically to the linked items with different extensions. The [external files](https://jellyfin.org/docs/general/server/media/external-files.html) page of the docs has a bit more detail of the options.
> 
> Or I could be wrong and it's undocumented and works fine, but you're throwing a monkey wrench into the scanner by not having your files in a season directory. Basically, the scanner expects your episodes to be inside a season directory with the relevant external files named identically next to them.
> 
> ```
> show name
>   season XX
>     episode S0XEXX.mkv
>     episode S0XEXX.srt
> ```
> 
> or
> 
> ```
> show name
>   episode S0XEXX.mkv
>   episode S0XEXX.srt
> ```
> 
> However, what you've done with your structure is kinda combine the two approaches and possibly confusing the server into thinking all the individual episodes are fine, _and_ the separate subs folder is it's own season. So I'm guessing you're winding up with duplicate entries, possibly linked together. If it's working in the server as you expect, I'd be super surprised. I just tried moving some subs into a separate folder and they're not being scanned in at all
> 
</details>

Of course it is not working on the server. 
I keep this `Subs` folder because it is given when i download the series. 
It kinda nice when i have multiple language for my case (I come from non english speaking country, i personally like to watch `en.sdh` subtitle, but when i need to share movies/series to my friend and family, i need to provide them with my native language subtitle too)
I guess i have to remove and restructure this Subs folder then.

<details>

> Edit: fwiw, when I have things laid out according to the docs, the flatten single season appears to work as intended, but I have the full season so I'm not sure if the missing episodes feature in the server would effect it (I personally think that feature is dumb).
> 
> ```
> Afro Samurai
> ├── banner.jpg
> ├── fanart.jpg
> ├── poster.jpg
> ├── Season 01
> │   ├── Afro Samurai - S01E01 - Revenge.en.srt
> │   ├── Afro Samurai - S01E01 - Revenge.mp4
> │   ├── Afro Samurai - S01E01 - Revenge.nfo
> │   ├── Afro Samurai - S01E01 - Revenge-thumb.jpg
> │   ├── Afro Samurai - S01E02 - The Dream Reader.en.srt
> │   ├── Afro Samurai - S01E02 - The Dream Reader.mp4
> │   ├── Afro Samurai - S01E02 - The Dream Reader.nfo
> │   ├── Afro Samurai - S01E02 - The Dream Reader-thumb.jpg
> ```
</details>

you might want to try _Alice in Borderland (2020)_. 
Season 2 has not started yet, but jellyfin has already listed season 2 with empty episodes if you have enabled `Settings > Display > Display missing episodes within seasons`

`Display missing episodes within seasons` feature might be not inline with your daily use case. 
For me, this feature serve as reminder that i have some missing episodes when i watch series with ongoing season, 
or there might be someone who did not know that their downloaded series are missing some episodes.

Of course there are others who did not like to wait watching ongoing series and choose to wait until it's completed.

Thank you for your reply..

**Comment by mcarlton00** [comment]
I think I might be getting things mixed up.  Is the file structure you're using for your subs actually a factor in this?  It seems like it might be more just the missing episodes piece, while the subs directory isn't actually influencing the situation much.

It's not really relevant to go over why I don't like the feature.  I'll summarize by saying it's got a literal pile of technical issues on the backend that can get transferred to clients (which this issue demonstrates), and it's seemingly the source of a never ending stream of support requests.  But that's besides the point, the code exists so we have to support it.  I'll need to spin up a new test server that I can enable the missing episodes on so it doesn't add a bunch of junk to the database of my normal installs.

**Comment by aiosk** [comment]
> I think I might be getting things mixed up. Is the file structure you're using for your subs actually a factor in this? It seems like it might be more just the missing episodes piece, while the subs directory isn't actually influencing the situation much.

that is my thought too,,
jellyfin recognize my Subs folder which is named `SeriesName -  S0XE0X` as episodes, even though it is a folder..
but i think that is more of jellyfin bug rather than jellycon one.

**Comment by mcarlton00** [comment]
I don't like the idea of adding special code to work around an edge case that's explicitly not supported by the server.  Especially when avoiding this behavior is as simple as moving your media files and your unsupported Subs folder into a more standard `Season 01` directory instead of in the show root (causing `Subs` to no longer be read as a season).

Closing in favor of #198 to fix the missing episodes/flatten seasons issue

**Pull request closed without merging**
